version: '3.8'

services:
  web:
    build: ./$DJANGO_PROJECT_NAME
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./$DJANGO_PROJECT_NAME/:/usr/src/$DJANGO_PROJECT_NAME/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=$DJANGO_PROJECT_NAME
    ports:
        - "6543:5432"

volumes:
  postgres_data:
